// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Loading/Background.vue')['default']
    Button: typeof import('./src/components/Clock/Button.vue')['default']
    Clock: typeof import('./src/components/Clock/Clock.vue')['default']
    ColorPicker: typeof import('./src/components/Sign/ColorPicker.vue')['default']
    Content: typeof import('./src/components/Animation/Content.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    HswInput: typeof import('./src/components/hsw-input.vue')['default']
    Input: typeof import('./src/components/Sign/Input.vue')['default']
    LeftMenu: typeof import('./src/components/Animation/LeftMenu.vue')['default']
    NavList: typeof import('./src/components/Animation/NavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/Step.vue')['default']
    StepItem: typeof import('./src/components/StepItem.vue')['default']
    Table: typeof import('./src/components/table.vue')['default']
    Text: typeof import('./src/components/Loading/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
